name: projeckflutter
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Perubahan di sini

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.8
  flutter_staggered_grid_view: ^0.4.0
  sidebarx: ^0.16.2
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  http: ^0.13.3  # Versi terbaru dari package http

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
